---
namespace: community
name: projet_role
version: 1.0
readme: README.md
authors:
  - Allan
description: Projet role  
license_file: COPYING
tags:
  - v1
repository: https://github.com/asemin08/templateProjet
documentation: https://github.com/asemin08/templateProjet
homepage: https://github.com/asemin08/templateProjet
issues: https://github.com/asemin08/templateProjet
build_ignore:
  - .gitignore
 